### ISSUE TITLE
Very slow performance with long lines and paint issue

### ISSUE THREAD

**Issue by dados** [TurboPack/SynEdit#177] opened 2022-02-17 15:14 UTC
Tested with single line files of various sizes.

Sizes 4kb, 8kb and 16kb where fine.

Tested also with 512Kb, 1Mb, 5Mb and 10Mb. And from 512Kb the single line file the performance degraded very much. 

For example If I loaded the 5Mb single line file and pushed the END button eventually the pointer and horizontal scrollbar updated but the text at the end of the line was not painted (no text was painted when cursor was at the end of the line)

**Comment by pyscripter** [comment] 2022-02-17 16:21
VS code has a limit of 10000 characters per line.

This is a duplicate of #166.

A fix was implemented that would automatically switch WordWrap on when line length exceeds 10000 (what VS Code does).  It was then removed.   Could you please try  the peformance with WordWrap one?

**Comment by dados** [comment] 2022-02-18 01:54
Having WordWrap makes a huge difference when scrolling through that single wrapped line. 
Editing that line is still very slow but about 3.5 - 4x faster with WordWrap on

Funny having a 5 or 10Mb. single line with WordWrap ON and going to the end of the line (with wordwrap it's the bottom) and adding the second line and start typing. Editing that second line works just fine, but if I push arrow up and go to the first line (long line) and try to edit that line every thing slows down.
I would say it takes about 1,8 seconds (without WordWrap it takes 7 seconds) after I type a single letter for it to appear with the 5Mb. line and about 3 seconds with 10mb line. 
And typing multiple characters at once just multiplies the waiting time by count of chars. 

Having erWrapwithRightEdge ON did nothing for the performance except when resizing a form with synedit aligned to client (did not have to change the text display width when resizing)

I think that the work on the latest SynEdit version is wonderful and I appreciate the work....But
I have a program that I've been developing and using for about 15 years now and I've compiled it with the new SynEdit version and it makes that program so frustrating to use as my main tool at work, just because of this lag with large lines. Just a 12k line is almost "unusable" to work with (no lag with the old SynEdit version on a 12k line)

I have not looked at the SynEdit code and I do not understand the reason behind the lag. But It would be wonderful if this could be optimized somehow without having to use WordWrap (it still lags with WordWrap)
Visual Studio, ConTEXT and Notepad++ are able to display and edit a 12K line without any lag

These tests where done by compiling a release and run without debugger in 64bit. (D11, Win10, Dell Precision i7)

**Comment by dados** [comment] 2022-02-18 10:45
Thanks 👍

**Comment by MShark67** [comment] 2022-02-19 12:12
I agree that this would be a low priority thing, but theoretically (and with limited knowledge of the challenges involved):

The speed issues all come down to performing actions on a text layout of an entire line when the line is very long.  The solution would be to work on a portion or "window" of the current line.  I've done the very simple test of using the initial portion of the current line instead of the entire thing.  Of course, my simple sample falls apart as soon as we scroll right.  In that case the layout "window" would have to shift as well along with knowing the exact pixel offset of the beginning of the window and determining the part of the line for the partial layout.  I'm not sure how that would work when combined with highlighting, though I'd think that highlighting could be turned off on such a wide file automatically.

Which, I'm guessing, is a lot of work, though the overall payoff could be impressive.  I also think that this discussion shouldn't minimize how well the control works now with all reasonable coding files (which is its purpose after all.)  The "wide file" issue is almost exclusively a "log" or "data" file issue, not a coding file issue.

**Comment by pyscripter** [comment] 2022-02-19 13:26
Just wait a bit...  A fix is coming.

**Comment by MShark67** [comment] 2022-02-19 14:59
Here are some sample files I use for testing.  These are, in no way, reasonable real-world files lol.  It's a simple 100 char select statement that highlights nicely, Repeated 20K chars per line, 50K chars per line, and 100K chars per line (the 100K one is good 
for non-highlight testing.)  10 lines per file.

[SynEditPerformanceTests.zip](https://github.com/TurboPack/SynEdit/files/8102381/SynEditPerformanceTests.zip)

**Comment by pyscripter** [comment] 2022-02-20 00:21
@dados @MShark67 
Have not finished yet but do try the latest version.

**Comment by pyscripter** [comment] 2022-02-20 02:18
I was going to implement Mark's suggestion above, but then I came across this: https://en.delphipraxis.net/topic/6360-string-optimization/.

Now it should be quite fast even with Syntax highlighting.

**Closed** 2022-02-20 02:26 UTC
Labels: duplicate

**Comment by MShark67** [comment] 2022-02-20 03:39
Wow!  Initial tests are impressive.  I'll test more tomorrow.  Well done!

**Comment by DGH2112** [comment] 2022-02-20 09:50
I can confirm that there is a remarkable improvement in performance from these changes on my ridiculously long and wide file with highlighting and without.
Thanks for this.

**Comment by DGH2112** [comment] 2022-02-20 10:04
I think I've found a different issue with further testing. If I go to the area of the file where it's wide and scroll to the right one column at a time using the scrollbar button I get the below-looking editor (the lines are not drawn on the right side of the editor) but if I scroll by pages horizontally (clicking to the left of the right scroll button) this doesn't happen.
![image](https://user-images.githubusercontent.com/19982149/154837535-20d5bc08-fd3a-4753-aeda-23b587373c76.png)

**Comment by MShark67** [comment] 2022-02-20 12:55
@DGH2112 I haven't been able to duplicate your issue here yet.  Does turning off theming or highlighting change the behavior?

**Comment by DGH2112** [comment] 2022-02-20 15:09
I've just tried without theming and got the same result. I've tried to find a rationale behind it but cannot. Some not so long lines do it and some extremely long lines do it. I thought it was lines greater than 255 chars but that doesn't seem to support what I'm seeing.

**Comment by DGH2112** [comment] 2022-02-20 15:17
I'm now also seeing issues with cursor position when CTRL+LEFT and CTRL+RIGHT. The cursor should be at the start of words but isn't. Also, the selection is not aligned with the cursor when this happens.
Now my data is TAB delimited, could this be causing something to not be calculated correctly?

**Comment by DGH2112** [comment] 2022-02-20 15:27
Okay, I think I've found the fundamental issue.
I replaced all the TAB characters with 2 spaces (took a while) and the scrolling/paint issue disappeared.
I do not know where in the code this will be by it must have something to do with calculating the width of a TAB character.

**Comment by pyscripter** [comment] 2022-02-20 15:52
Fixed.  Please try again.

**Comment by pyscripter** [comment] 2022-02-20 16:11
@MShark67 While looking at this I found an issue with horizontal scrolling and esScrollPastEOL.

It is kind of hard to provide instructions on how to replicate.  I could only replicate it with long lines.
- Scroll to the right so that the horizontal scroll bar appears and set the cursor outside text area.
- Then drag the horizontal scroll bar to the right and keep pressing it.
- It gets into an infinite loop.  SetLeftChar - UpdateScrollBars -WMHSCROLL-SetLeftChar.

Still have not found a way to resolve it.

**Comment by MShark67** [comment] 2022-02-20 16:38
I'll take a look!  I notice that the caret positioning is now amazingly fast for wide lines, however any painting that happens out there is slower.   I see the Layout is using lastchar to limit the string, but not firstchar.   That may be completely as intended, but everything else is so fast now that it stands out.  My timings for my 100K file but increasing the linecount to fill the screen is:

Paint: 22ms  LeftChar: 631             <-- Near the left side super fast
Paint: 1613ms  LeftChar: 99866     <-- Near the end (not in debug mode, no highlighting, no hard tabs.)

I almost hate to bring it up, the improvements are stellar, but I like to be thorough.  Fantastic work!

**Comment by DGH2112** [comment] 2022-02-20 17:23
> Fixed. Please try again.

@pyscripter Yes this seems to have done the trick, thank you.

**Comment by MShark67** [comment] 2022-02-20 17:55
@pyscripter   I haven't been able to cause it to happen here, but it sounds like it gets into a bit of a feedback loop.  My thought is to not call UpdateScrollBars if IsScrolling is true (I assume from your steps above that this happens while IsScrolling is true.)

**Comment by pyscripter** [comment] 2022-02-20 17:59
> I notice that the caret positioning is now amazingly fast for wide lines, however any painting that happens out there is slower. I see the Layout is using lastchar to limit the string, but not firstchar. That may be completely as intended, 

I indent to implement that, but it will take quite a few tricky changes, so I decided to leave it for another day.

**Comment by pyscripter** [comment] 2022-02-20 18:06
> I assume from your steps above that this happens while IsScrolling is true
Yes.  SetLeftChar - UpdateScrollBars -WMHSCROLL-SetLeftChar

**Comment by MShark67** [comment] 2022-02-20 18:52
Hmmm, I seem to have a hard time getting it to happen.  I'll keep trying.   Note that I didn't change any of the calls used, it's always used SetScrollInfo (which I believe is the modern way, at least according to Microsoft's documentation.)  The ScrollPastEOL situation is unique in that the range and position both are changing at once. I could separate SIF_RANGE and SIF_POS to separate calls if you think that's the issue.  That note about calling SetScrollPos is certainly true, I think they just mean that you need to do if you change the scroll box programmatically (such as moving the caret via keystrokes)

If you just change UpdateScrollbars like so, does it fix the problem for you?  I'm still trying to get it to happen.

```
procedure TCustomSynEdit.UpdateScrollBars;
begin
  if not HandleAllocated or (PaintLock <> 0) then
    Include(fStateFlags, sfScrollbarChanged)
  else begin
    Exclude(fStateFlags, sfScrollbarChanged);
    if not FIsScrolling then
      if FSynEditScrollBars.UpdateScrollBars then
        Update;
  end;
end;

```

**Comment by MShark67** [comment] 2022-02-20 18:58
[update] sorry, more testing needed on my part.  I'll report back

**Comment by pyscripter** [comment] 2022-02-20 19:06
I looked at how Vcl implements Scrolling say in TCategoryButtons
TCategoryButtons.Resize calls SetScrollInfo
and 
WMHScroll/WMVScroll call ScrollPosChanged which calls SetScrollPos

The problem we have is that horizontal if eoScrollPastEOL is True also changes the scrollbar range!

**Comment by MShark67** [comment] 2022-02-20 19:07
Agreed!   My current fix is to use SIF_POS instead of SIF_ALL if IsScrolling.

**Comment by pyscripter** [comment] 2022-02-20 19:08
> Agreed! My current fix is to use SIF_POS instead of SIF_ALL if IsScrolling.

Do you have some code I can try?

**Comment by MShark67** [comment] 2022-02-20 19:10
Here's my quick fix:

[SynEditScrollBars.zip](https://github.com/TurboPack/SynEdit/files/8104751/SynEditScrollBars.zip)

**Comment by pyscripter** [comment] 2022-02-20 19:15
> Here's my quick fix:

Still the same infinite loop...

**Comment by MShark67** [comment] 2022-02-20 19:18
Darn it!  I really thought that might be it.  I wish I could cause it, maybe it's a different setting I'm using.  I'll keep at it.

**Comment by pyscripter** [comment] 2022-02-20 21:59
@MShark67 
I have committed a fix, based on your idea.  Please have a look and test.
Note the calls to RedrawWindow.   For some reason I had to invalidate the non-client area for the scrollbars to paint correctly after scrolling.  This maybe relevant to the discussion about UpdateWindow (maybe not).

**Comment by MShark67** [comment] 2022-02-20 22:15
Awesome!  I've been going at it from a different perspective.  I noticed that our "leftchar" based updating scrollinfo values didn't match our "thumbtrack" based values (so the set value would be range adjusted during the feedback loop.).  I'm not sure if that would lead to the infinite loop issue, but it seemed like a problem to me.  I managed to get that "fixed", though I don't really know if it was an issue in the first place.  I'll take a look at your changes and see if it makes sense to merge my changes into it.

**Comment by MShark67** [comment] 2022-02-21 00:49
Fix looks good!  I think this is the way to go.   Interestingly enough, if I comment out the "if isscrolling" check I can recreate the issue that I haven't been able to see so far!  That makes me feel better about the fix technique... well done.   I'll have some very minor adjustments that fix the range fix issue I mentioned (which is unrelated to the infinite loop issue, but I think good to fix.)  Currently we scale all the values based on charwidth, but we could also just go back to doing it "per char" which makes the code a bit cleaner I think.  Let me know if you'd like me to do that as well (I've already done it while I was trying to verify other issues.)  Also, it looks like the line ends got messed up on the commit.

**Comment by pyscripter** [comment] 2022-02-21 01:15
Just committed an improvement that gets rid of the RedrawWindow stuff (the need to use them bothered me), by calling SetScrollPos.  

Why don't you submit one or more PRs. whichever is convenient.   

Keeping track of the scrolling in terms of "notional" chars may indeed simplify the code.  I am happy to go back.
But we should always keep in mind that chars don't have the same width, and many WideChars can be displayed as a single grapheme.   But since horizontal scrolling is based on LeftChar then it makes sense to base the scrolling on that as well.

**Comment by MShark67** [comment] 2022-02-21 01:40
My understanding is you aren't supposed to use setscrollpos anymore.  The docs say: Note  The SetScrollPos function is provided for backward compatibility. New applications should use the [SetScrollInfo](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setscrollinfo) function.  Do you mind if I change that to use SetScrollInfo with sif_pos instead?  It will have the same affect, basically we're just bypassing the LeftChar -> setpos with wrong value issue by setting it directly (along with the redraw flag.)

**Comment by pyscripter** [comment] 2022-02-21 01:49
No I don't mind but where does it say so?  https://docs.microsoft.com/en-us/windows/win32/controls/wm-vscroll for example says that SetScrollPos should be called.

**Comment by MShark67** [comment] 2022-02-21 01:57
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setscrollpos

**Comment by pyscripter** [comment] 2022-02-21 02:00
I see. Good go ahead.  It takes a bit more code, but it is more update.

**Comment by pyscripter** [comment] 2022-02-22 14:46
@dados @MShark67 
Completed the optimizations for long lines.  Please test again for performance but also for errors I may have inadvertently introduced. 

The only case which is not optimized is when you are viewing the far right and  the displayed text includes hard tabs.
If you want fast editing of say tab delimited files with very long lines, you can still get speed by setting the tabwidth to 1.

**Comment by dados** [comment] 2022-02-22 14:50
Thank you so much 👍  I'll test and post my results

**Comment by MShark67** [comment] 2022-02-22 16:16
I'm seeing amazing performance on my test files.  I haven't noticed any problems so far.  @dados, are you only seeing performance issues or are you seeing behavior or painting issues?  Are you trying outside of debugging and with highlighers turned off?

**Comment by dados** [comment] 2022-02-22 16:39
Yes I agree, the performance has improved very much.
I'm trying outside debugging without highlighters.
Here is my test program
[SynEditBenchTest.zip](https://github.com/TurboPack/SynEdit/files/8118425/SynEditBenchTest.zip)
Start the program and load data via the button and try to move around with arrow key's and see if you experience the delay as well on the long line

**Comment by pyscripter** [comment] 2022-02-22 17:26
@dados   I can reproduce the delay.  However this file has 11 million characters in one line.

**Comment by dados** [comment] 2022-02-22 17:32
Yes, like I said I used an extra large line to exaggerate any delay. 
Everything is extremely fast on the huge line: editing, home/end, cursor replacement with mouse
And then there is this huge difference when using the arrow keys

**Comment by pyscripter** [comment] 2022-02-22 21:11
ValidTextPos  optimized.  Please try again.

**Comment by dados** [comment] 2022-02-22 21:49
That did it, super well done :) 👍

**Comment by MShark67** [comment] 2022-02-22 23:38
@pyscripter, Amazing work!  Bravo!

**Comment by pyscripter** [comment] 2022-02-22 23:41
Thanks for pushing me to do this and for contributing and  testing!

**Comment by pyscripter** [comment] 2022-02-23 02:44
Next thing is indicators.  I think you will like it.

**Comment by pyscripter** [comment] 2022-02-23 02:45
@dados You may want to update your comment in https://en.delphipraxis.net/topic/6277-synedit-just-got-a-major-uplift

**Comment by dados** [comment] 2022-02-23 09:36
Tested that 10Mb single line with WordWrap and with and without eoWrapWithRightEdge (no highlighting) 
Total time loading and painting is little over 4 seconds. Typing any character (editing) takes 4 seconds for each char.
There might still be some room for performance improvement :)

**Comment by dados** [comment] 2022-02-23 12:11
Ok this might take some work and serious calculating
I'm trying to figure it out, but I'm just not that familiar with the synedit code or a good of a programmer to work it out :)
It's just not easy as calculating the peace of the line that should be visible messes with the vertical scrollbar

**Comment by pyscripter** [comment] 2022-02-23 12:14
Yes it is that easy.

**Comment by dados** [comment] 2022-02-23 12:16
Well I tried but It messed up the vertical scrollbar. I guess I missed something

**Comment by pyscripter** [comment] 2022-02-25 06:18
@dados  Word wrapping has been optimized.   Please try again and report back.

**Comment by dados** [comment] 2022-02-25 13:16
Genius! :) 
Tested with all sorts of property option combinations and could not find any bugs.
Thank you 👍

**Comment by dados** [comment] 2022-02-25 14:19
Editing and selecting a text block with a mouse is super fast without highlighting but super slow with highlighting especially at the end of the line.

I feel bad for keep pointing out stuff to optimize cause you have done such an excellent job.
And when to stop. I could load up a 1Gb single line xml file and keep pointing out performance issues with huge lines :)
But this is not that kind of an editor.

Thank you 👍

**Comment by MShark67** [comment] 2022-02-25 14:26
> I could load up a 1Gb single line
lol. Exactly.  The fact that we need to throw that much at it to slow it down is pretty amazing.  What a job pyscripter has done!

**Comment by dados** [comment] 2022-02-25 14:30
I agree!

**Comment by pyscripter** [comment] 2022-02-25 14:44
> Editing and selecting a text block with a mouse is super fast without highlighting but super slow with highlighting

Does it matter what highlighter (i.e is this specific to some highlighter(s)? With wordwrap or without?

**Comment by dados** [comment] 2022-02-25 16:14
Yes highlighter types matter....some tests

I tested with XML highlighter and it was a slower with wordwrap. ctrl+home is fast but ctrl+end is slow (with wordwrap)
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~350msec. (without wordwrap)
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~5400msec. (with wordwrap)
block select with mouse at the end of the line ~ 15 sek.
eoWrapWithRightEdge + RightEdge width or without eoWrapWithRightEdge and edit area width did not seem to matter, maby about 4% from wide to 6 x shorter area (amount of wrapped lines from a single line)

Java:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~550msec. (without wordwrap)
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~12,2 seconds (with wordwrap) never worked really. Cause 12 seconds was enough to make it go (not responding) and if synedit or form lost focus while working it would produce paint loop that each took 12 seconds and I just terminated it.
3 out of 4 test lead to paint loop and progam not responding. and of course cpu at max.
ie. Worked sometimes if I was 

SQL:
ctrl+home = ~45msec. (without wordwrap)
ctrl+end = ~750msec. (without wordwrap)
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~16,5 seconds (with wordwrap) did not actually end - same problem as with java

Python:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~1650msec. (without wordwrap)
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~40 seconds (with wordwrap) same issue- paint loops and not responding

JSON:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~240msec. (without wordwrap)
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~3 seconds (with wordwrap)  OK

**Comment by pyscripter** [comment] 2022-02-25 17:40
Please try again.  I have committed some changes.

**Comment by dados** [comment] 2022-02-25 18:36
Well that was fast :)

just something I noticed: paint event fires before CommandProcessed without wordwrap but with wordwrap paint event fires after CommandProcessed 

XML:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~350msec. (without wordwrap) --> now ~220msec
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~5400msec. (with wordwrap)  --> now ~175msec
editing without wordwrap -> ~150msec at front and ~400msec at the end
editing with wordwrap -> ~390msec at front and ~540msec at the end 

Java:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~550msec. (without wordwrap)  --> now ~430msec.
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~12,2 seconds (with wordwrap) --> now ~340msec.
editing without wordwrap -> ~335msec at front and ~770msec at the end
editing with wordwrap -> ~580msec at front and ~1000msec at the end 

SQL:
ctrl+home = ~45msec. (without wordwrap)
ctrl+end = ~750msec. (without wordwrap) --> now ~610msec.
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~16,5 seconds (with wordwrap) --> now ~540msec.
editing without wordwrap -> ~563msec at front and ~1150msec at the end
editing with wordwrap -> ~780msec at front and ~1270msec at the end 

Python:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~1650msec. (without wordwrap) --> now ~1550msec.
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~40 seconds (with wordwrap)  --> now ~1500msec.
editing without wordwrap -> ~1500msec at front and ~3000msec at the end  
editing with wordwrap -> ~1670msec at the front and ~3180msec at the end
When editing at the end of the line the command was processed after ~1700msec and the paint took ~1480msec (45% of total  time) so the paint takes alot more time at the end (no time at all at the front)

JSON:
ctrl+home = 0-16msec. (without wordwrap)
ctrl+end = ~240msec. (without wordwrap)  --> now ~160msec.
ctrl+home = 0-30msec. (with wordwrap)
ctrl+end = ~3 seconds (with wordwrap)  --> now ~80msec.
editing without wordwrap -> ~100msec at front and ~270msec at the end
editing with wordwrap -> ~330msec at the front and 480msec at the end

**Comment by pyscripter** [comment] 2022-02-25 18:42
> just something I noticed: paint event fires before CommandProcessed without wordwrap but with wordwrap paint event fires after CommandProcessed

Is this an issue?  It may have to do with UpdateScrollbars and calling Update (see separate issue).

How big are the files you are using?

**Comment by dados** [comment] 2022-02-25 18:47
No it's not an issue for me, just something I noticed.
I was working with a 10mb file. I used the same xml file in all tests (all highlighters)

**Comment by pyscripter** [comment] 2022-02-25 18:55
> Does that not test the performance of each highlighter enough?

Yes it does.

Editing is always going to be slow with such long with word wrapping and such long lines.  In any case I think I am done for now.  If you find any specific bottlenecks in the code I will then have another look.

Thanks very much for helping improve the speed of SynEdit.

**Comment by dados** [comment] 2022-02-25 19:13
It was my pleasure. Thank you so much
