### ISSUE TITLE
TSynCssSyn infinite loop

### ISSUE THREAD

**Issue by PaulvanHelden** [TurboPack/SynEdit#253] opened 2024-03-16 10:01 UTC
SynHighlighterCSS.pas line 610 returns True for a $ character, but the case block starting line 620 does not handle a $, resulting in an infinite loop.

My solution was to simply remove '$' on line 610

**Comment by pyscripter** [comment] 2024-03-16 11:27
Duplicate of #241

**Closed by pyscripter** 2024-03-16 11:27 UTC
