### ISSUE TITLE
Memory leak in SynHighlighterVBScript

### ISSUE THREAD

**Issue by selticq** [TurboPack/SynEdit#68] opened 2021-06-06 10:25 UTC
A memory leak is detected when using the TSynVBScriptSyn component in a project targeting the Windows 64 platform (not when targeting Windows 32 platform).

Delphi version: 10.4.2 Sydney

How to reproduce :

Create a new VCL project targeting the Windows 64 platform.

In the .dpr, add :

`ReportMemoryLeaksOnShutdown := true;`

Add a TSynVBScriptSyn component to the form.

Run and close.

Regards,

Selticq

[code.zip](https://github.com/TurboPack/SynEdit/files/6604007/code.zip)

**Comment by pyscripter** [comment] 2021-06-06 11:14
@JaFi-cz Could you please take a look at this?  It is probably caused by your submitted changes.

**Comment by selticq** [comment] 2021-06-06 16:25
At line 266 of SynHighlighterVBScript, in the constructor of TSynVBScriptSyn, i think this : 

`fKeywords := TSynHashEntryList.Create;`

is never freed.

**Comment by JaFi-cz** [comment] 2021-06-06 17:31
You might be right. I will add destroy section into VBScript highlighter and release the fKeywords. 
I will check other highlighters too, cause it's common construction from the past and the list is present in 24 highlighters.

**Comment by JaFi-cz** [comment] 2021-06-06 17:43
I checked rest of highlighter and VBScript highlighter was the only one with missing destroy method

**Comment by selticq** [comment] 2021-06-06 17:46
yes, I did not detect any error in the other highlighters, it was the only one.

**Comment by pyscripter** [comment] 2021-06-14 12:33
Fixed with #66

**Closed by pyscripter** 2021-06-14 12:33 UTC
Labels: PR invited
