### ISSUE TITLE
SynEdit install error on Delphi 11.2

### ISSUE THREAD

**Issue by Henrik9691** [TurboPack/SynEdit#230] opened 2022-09-09 11:24 UTC
Just upgraded to Delphi 11.2, and wanted to install SynEdit via GitIt Package manager in Delphi 11.2 on Windows 11 (ARM) 

The installation ended with an error.

<img width="913" alt="2022-09-09_10-02-24" src="https://user-images.githubusercontent.com/113128813/189338657-36396bec-8428-487b-90b9-6ae9af084717.png">

Log from when trying to install the component.

Checking project dependencies...
Compiling SynEditDD.dproj (Release, Win32)
brcc32 command line for "SynEditDD.vrc"
  c:\program files (x86)\embarcadero\studio\22.0\bin\cgrc.exe -c65001 SynEditDD.vrc -foSynEditDD.res 
dcc32 command line for "SynEditDD.dpk"
  c:\program files (x86)\embarcadero\studio\22.0\bin\dcc32.exe -$J+ -$D0 -$L- -$Y- --no-config -M -Q -Z -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DRELEASE -I..\..\..\Source;"c:\program files (x86)\embarcadero\studio\22.0\lib\Win32\release";
  C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports;C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports\Win32;"c:\program files 
  (x86)\embarcadero\studio\22.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp;"c:\program files (x86)\embarcadero\studio\22.0\include" 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl -LNC:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp -NU.\Win32\Release -NSSystem.Win;
  Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Vcl;Winapi; -O..\..\..\Source;"c:\program files 
  (x86)\embarcadero\studio\22.0\lib\Win32\release";C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports;
  C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports\Win32;"c:\program files (x86)\embarcadero\studio\22.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp;"c:\program files (x86)\embarcadero\studio\22.0\include" -R..\..\..\Source;"c:\program files 
  (x86)\embarcadero\studio\22.0\lib\Win32\release";C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports;
  C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports\Win32;"c:\program files (x86)\embarcadero\studio\22.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp;"c:\program files (x86)\embarcadero\studio\22.0\include" -U..\..\..\Source;"c:\program files 
  (x86)\embarcadero\studio\22.0\lib\Win32\release";C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports;
  C:\Users\user\Documents\Embarcadero\Studio\22.0\Imports\Win32;"c:\program files (x86)\embarcadero\studio\22.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\22.0\Dcp;"c:\program files (x86)\embarcadero\studio\22.0\include" -K00400000 --description:"TurboPack 
  SynEdit Delphi designtime package" -JL -NB..\cpp\Win32\Release -NH..\cpp\Win32\Release -NO..\cpp\Win32\Release  SynEditDD.dpk   
[dcc32 Fatal Error] SynEditDR.dpk(31): E2225 Never-build package 'designide' must be recompiled
[dcc32 Fatal Error] SynEditDD.dpk(36): E2202 Required package 'SynEditDR' not found
Failed
Elapsed time: 00:00:00.3
SynEditDR.dpk(1): Line endings are LF, but RAD Studio requires CRLF. Consider converting or check your source control settings.

**Comment by pyscripter** [comment] 2022-10-24 02:18
Duplicate of #229

Until the GetIt version is fixed use this repo instead.

**Closed by pyscripter** 2022-10-24 02:18 UTC
Labels: duplicate
